/* Regenerates js/icons.js from the Lucide icon set (lucide-react-native in frontend/node_modules).
   Run from frontend/: node prototype/scripts/build-icons.mjs */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const proto = join(here, '..');
const lucide = join(proto, '..', 'node_modules', 'lucide-react-native');
const iconDir = join(lucide, 'dist', 'esm', 'icons');
const version = JSON.parse(readFileSync(join(lucide, 'package.json'), 'utf8')).version;

/* Prototype name → Lucide name (first one that exists wins). */
const MAP = {
  home: ['house'],
  reels: ['clapperboard'],
  mask: ['venetian-mask'],
  chat: ['message-circle'],
  user: ['user'],
  search: ['search'],
  bell: ['bell'],
  heart: ['heart'],
  comment: ['message-circle'],
  send: ['send'],
  more: ['ellipsis'],
  moreV: ['ellipsis-vertical'],
  plus: ['plus'],
  plusSquare: ['square-plus'],
  x: ['x'],
  back: ['chevron-left'],
  chevronRight: ['chevron-right'],
  chevronDown: ['chevron-down'],
  chevronUp: ['chevron-up'],
  settings: ['settings'],
  camera: ['camera'],
  image: ['image'],
  check: ['check'],
  checks: ['check-check'],
  eye: ['eye'],
  eyeOff: ['eye-off'],
  shield: ['shield'],
  shieldCheck: ['shield-check'],
  flag: ['flag'],
  ban: ['ban'],
  crown: ['crown'],
  sparkles: ['sparkles'],
  mail: ['mail'],
  logout: ['log-out'],
  moon: ['moon'],
  sun: ['sun'],
  monitor: ['monitor'],
  help: ['circle-question-mark', 'circle-help'],
  file: ['file-text'],
  radar: ['radar'],
  card: ['credit-card'],
  wallet: ['wallet'],
  bank: ['landmark'],
  phone: ['smartphone'],
  upload: ['upload'],
  trash: ['trash-2', 'trash'],
  edit: ['pencil'],
  users: ['users'],
  userPlus: ['user-plus'],
  userCheck: ['user-check'],
  chart: ['chart-line', 'line-chart'],
  dashboard: ['layout-dashboard'],
  rupee: ['indian-rupee'],
  alert: ['triangle-alert', 'alert-triangle'],
  info: ['info'],
  lock: ['lock'],
  unlock: ['lock-open', 'unlock'],
  gift: ['gift'],
  grid: ['grid-3x3', 'grid-3-x-3'],
  play: ['play'],
  pause: ['pause'],
  music: ['music'],
  filter: ['funnel', 'filter'],
  refresh: ['refresh-cw'],
  key: ['key-round'],
  clock: ['clock'],
  arrowRight: ['arrow-right'],
  arrowUp: ['arrow-up'],
  arrowDown: ['arrow-down'],
  pinOff: ['map-pin-off'],
  map: ['map'],
  pin: ['map-pin'],
  bluetooth: ['bluetooth'],
  bluetoothOff: ['bluetooth-off'],
  ruler: ['ruler'],
  history: ['history', 'rotate-ccw-clock'],
  repeat: ['repeat'],
  smile: ['smile', 'face-slightly-smiling'],
  link: ['link'],
  menu: ['menu'],
  download: ['download'],
  zap: ['zap'],
  headset: ['headset'],
  devices: ['monitor-smartphone'],
  star: ['star'],
  paperclip: ['paperclip'],
  globe: ['globe'],
  inbox: ['inbox'],
  flip: ['switch-camera'],
  type: ['type'],
  sliders: ['sliders-horizontal'],
  aperture: ['aperture'],
  bolt: ['zap'],
  boltOff: ['zap-off'],
  hash: ['hash'],
  layers: ['layers'],
  /* Used by the Premium tab instead of emoji */
  messageHeart: ['message-circle-heart'],
  heartHandshake: ['heart-handshake'],
  mailOpen: ['mail-open'],
  partyPopper: ['party-popper'],
  hand: ['hand'],
  circleCheck: ['circle-check'],
  calendar: ['calendar'],
  badgeCheck: ['badge-check'],
  infinity: ['infinity'],
};

/* Media controls read better solid. */
const FILLED = new Set(['play', 'pause']);

const attrs = (o) => Object.entries(o).filter(([k]) => k !== 'key').map(([k, v]) => `${k}="${v}"`).join(' ');

function load(name) {
  const f = join(iconDir, `${name}.mjs`);
  if (!existsSync(f)) return null;
  const src = readFileSync(f, 'utf8');
  const m = src.match(/const __iconData = (\{[\s\S]*?\n\});/);
  if (!m) throw new Error(`Could not parse ${name}`);
  // eslint-disable-next-line no-new-func
  return Function(`return ${m[1]}`)().node;
}

const out = [];
const missing = Object.entries(MAP).filter(([, names]) => !names.some(n => existsSync(join(iconDir, `${n}.mjs`))));
if (missing.length) throw new Error(`No Lucide icon found for: ${missing.map(([k, n]) => `${k} (${n.join(', ')})`).join('; ')}`);
for (const [key, names] of Object.entries(MAP)) {
  let node = null;
  for (const n of names) { node = load(n); if (node) break; }
  const fill = FILLED.has(key) ? ' fill="currentColor"' : '';
  const body = node.map(([tag, a]) => `<${tag} ${attrs(a)}${fill}/>`).join('');
  out.push(`    ${key}: '${body.replace(/'/g, "\\'")}',`);
}

const tpl = readFileSync(join(proto, 'js', 'icons.js'), 'utf8');
const start = tpl.indexOf('  const P = {');
const end = tpl.indexOf('  };', start) + 4;
const header = `/* Icons: Lucide v${version} (ISC, https://lucide.dev), generated by scripts/build-icons.mjs. Usage: Icon('home', 22) */\n(function () {\n`;
const next = header + `  const P = {\n${out.join('\n')}\n  };` + tpl.slice(end);
writeFileSync(join(proto, 'js', 'icons.js'), next);
console.log(`Wrote ${out.length} Lucide icons to js/icons.js`);
